### ISSUE TITLE
输出结果尺寸与原序列不一致

### ISSUE THREAD

**Issue by EderOdan** [yzxing87/pytorch-deep-video-prior#2]
Hi，首先非常感谢您愿意给出pytroch版本的DVP，对于学习DVP真的帮大忙了！
在复现您论文结果的过程中，发现DVP输出结果尺寸与原图像序列不一致。
例如，在demo中的上色序列为854 * 480，而test.sh输出结果为 832 * 480。在demo其他任务中也是这样。

请问这种情况正常吗？
因为我希望计算结果的PSNR值，但是被这个问题所困扰着。希望您能为我解答这个问题，非常感谢！

**Comment by yzxing87** [comment]
Hi, glad this implementation can help you. 

The shape mismatch problem is caused by [this line](https://github.com/yzxing87/pytorch-deep-video-prior/blob/main/main_IRT.py#L100). We crop the input to make its height and width are multiples of 32 to meet the constraint of original Unet downsample and upsample procedure. If you just want to reproduce our quantitative results, you can ignore this and crop the processed frames accordingly. If not, you can check this [Unet implementation](https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_parts.py#L63) which pads the upsample procedure to make Unet can handle any size of input. We have test this implementation and can obtain perceptually similar results.

**Comment by EderOdan** [comment]
Thank you so much for your reply!
